apiVersion: v1
kind: PersistentVolume
metadata:
  name: lss-pv
  namespace: parasoft-ns
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /home/docker/vol/lss
  
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lss-pvc
  namespace: parasoft-ns
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi
  volumeName: lss-pv