apiVersion: v1
kind: Service
metadata:
  name: datarepo-service
  namespace: parasoft-ns
spec:
  selector:
    tag: datarepo
  type: NodePort
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
    nodePort: 30017
