apiVersion: v1
kind: PersistentVolume
metadata:
  name: datarepo-pv
  namespace: parasoft-ns
spec:
  capacity:
    storage: 3Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /home/docker/vol/datarepo
 
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datarepo-pvc
  namespace: parasoft-ns
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 3Gi
  volumeName: datarepo-pv