apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
  namespace: parasoft-ns
spec:
  replicas: 1
  serviceName: mariadb
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      volumes:
      - name: mariadb-storage
        persistentVolumeClaim:
          claimName: mariadb-storage-pvc
      - name: mariadb-backup
        persistentVolumeClaim:
          claimName: mariadb-backup-pvc

      containers:
      - name: mariadb
        image: mariadb:latest
        env:
        - name: MARIADB_ROOT_PASSWORD
          value: "root"
        ports:
        - containerPort: 3306
          name: mariadb
        volumeMounts:
        - name: mariadb-storage
          mountPath: /var/lib/mysql
        - name: mariadb-backup
          mountPath: /backup
