apiVersion: v1
kind: PersistentVolume
metadata:
  name: soavirt-pv
  namespace: parasoft-ns
spec:
  capacity:
    storage: 3Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /home/docker/vol/soavirt
 
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: soavirt-pvc
  namespace: parasoft-ns
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 3Gi
  volumeName: soavirt-pv