apiVersion: v1
kind: Service
metadata:
  name: ctp-metrics
  namespace: parasoft-ns
spec:
  type: NodePort
  selector:
    app: ctp-metrics
  ports:
    - port: 5000
      name: http
      nodePort: 30500
