apiVersion: v1
kind: Service
metadata:
  name: ctp-service
  namespace: parasoft-ns
spec:
  selector:
    app: ctp
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30081